// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network.implementation;

import com.azure.resourcemanager.network.fluent.models.ExpressRouteLinkInner;
import com.azure.resourcemanager.network.models.ExpressRouteLink;
import com.azure.resourcemanager.network.models.ExpressRouteLinkAdminState;
import com.azure.resourcemanager.network.models.ExpressRouteLinkConnectorType;
import com.azure.resourcemanager.network.models.ExpressRouteLinkMacSecConfig;
import com.azure.resourcemanager.network.models.ProvisioningState;

public final class ExpressRouteLinkImpl implements ExpressRouteLink {
    private ExpressRouteLinkInner innerObject;

    private final com.azure.resourcemanager.network.NetworkManager serviceManager;

    ExpressRouteLinkImpl(
        ExpressRouteLinkInner innerObject, com.azure.resourcemanager.network.NetworkManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String etag() {
        return this.innerModel().etag();
    }

    public String routerName() {
        return this.innerModel().routerName();
    }

    public String interfaceName() {
        return this.innerModel().interfaceName();
    }

    public String patchPanelId() {
        return this.innerModel().patchPanelId();
    }

    public String rackId() {
        return this.innerModel().rackId();
    }

    public ExpressRouteLinkConnectorType connectorType() {
        return this.innerModel().connectorType();
    }

    public ExpressRouteLinkAdminState adminState() {
        return this.innerModel().adminState();
    }

    public ProvisioningState provisioningState() {
        return this.innerModel().provisioningState();
    }

    public ExpressRouteLinkMacSecConfig macSecConfig() {
        return this.innerModel().macSecConfig();
    }

    public ExpressRouteLinkInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
