// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network.implementation;

import com.azure.resourcemanager.network.fluent.models.ExpressRouteGatewayInner;
import com.azure.resourcemanager.network.fluent.models.ExpressRouteGatewayListInner;
import com.azure.resourcemanager.network.models.ExpressRouteGateway;
import com.azure.resourcemanager.network.models.ExpressRouteGatewayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public final class ExpressRouteGatewayListImpl implements ExpressRouteGatewayList {
    private ExpressRouteGatewayListInner innerObject;

    private final com.azure.resourcemanager.network.NetworkManager serviceManager;

    ExpressRouteGatewayListImpl(
        ExpressRouteGatewayListInner innerObject, com.azure.resourcemanager.network.NetworkManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<ExpressRouteGateway> value() {
        List<ExpressRouteGatewayInner> inner = this.innerModel().value();
        if (inner != null) {
            return Collections
                .unmodifiableList(
                    inner
                        .stream()
                        .map(inner1 -> new ExpressRouteGatewayImpl(inner1, this.manager()))
                        .collect(Collectors.toList()));
        } else {
            return Collections.emptyList();
        }
    }

    public ExpressRouteGatewayListInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
