// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network.implementation;

import com.azure.resourcemanager.network.fluent.models.ExpressRouteServiceProviderInner;
import com.azure.resourcemanager.network.models.ExpressRouteServiceProvider;
import com.azure.resourcemanager.network.models.ExpressRouteServiceProviderBandwidthsOffered;
import com.azure.resourcemanager.network.models.ProvisioningState;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public final class ExpressRouteServiceProviderImpl implements ExpressRouteServiceProvider {
    private ExpressRouteServiceProviderInner innerObject;

    private final com.azure.resourcemanager.network.NetworkManager serviceManager;

    ExpressRouteServiceProviderImpl(
        ExpressRouteServiceProviderInner innerObject, com.azure.resourcemanager.network.NetworkManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public Map<String, String> tags() {
        Map<String, String> inner = this.innerModel().tags();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public List<String> peeringLocations() {
        List<String> inner = this.innerModel().peeringLocations();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<ExpressRouteServiceProviderBandwidthsOffered> bandwidthsOffered() {
        List<ExpressRouteServiceProviderBandwidthsOffered> inner = this.innerModel().bandwidthsOffered();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public ProvisioningState provisioningState() {
        return this.innerModel().provisioningState();
    }

    public String id() {
        return this.innerModel().id();
    }

    public ExpressRouteServiceProviderInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
