// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network.implementation;

import com.azure.resourcemanager.network.fluent.models.SecurityGroupViewResultInner;
import com.azure.resourcemanager.network.models.SecurityGroupNetworkInterface;
import com.azure.resourcemanager.network.models.SecurityGroupViewResult;
import java.util.Collections;
import java.util.List;

public final class SecurityGroupViewResultImpl implements SecurityGroupViewResult {
    private SecurityGroupViewResultInner innerObject;

    private final com.azure.resourcemanager.network.NetworkManager serviceManager;

    SecurityGroupViewResultImpl(
        SecurityGroupViewResultInner innerObject, com.azure.resourcemanager.network.NetworkManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<SecurityGroupNetworkInterface> networkInterfaces() {
        List<SecurityGroupNetworkInterface> inner = this.innerModel().networkInterfaces();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public SecurityGroupViewResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
