// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network.implementation;

import com.azure.resourcemanager.network.fluent.models.ServiceTagsListResultInner;
import com.azure.resourcemanager.network.models.ServiceTagInformation;
import com.azure.resourcemanager.network.models.ServiceTagsListResult;
import java.util.Collections;
import java.util.List;

public final class ServiceTagsListResultImpl implements ServiceTagsListResult {
    private ServiceTagsListResultInner innerObject;

    private final com.azure.resourcemanager.network.NetworkManager serviceManager;

    ServiceTagsListResultImpl(
        ServiceTagsListResultInner innerObject, com.azure.resourcemanager.network.NetworkManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String name() {
        return this.innerModel().name();
    }

    public String id() {
        return this.innerModel().id();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String changeNumber() {
        return this.innerModel().changeNumber();
    }

    public String cloud() {
        return this.innerModel().cloud();
    }

    public List<ServiceTagInformation> values() {
        List<ServiceTagInformation> inner = this.innerModel().values();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public String nextLink() {
        return this.innerModel().nextLink();
    }

    public ServiceTagsListResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
