// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.management.SubResource;
import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.ApplicationGatewayOnDemandProbe;
import com.azure.resourcemanager.network.models.ApplicationGatewayProtocol;

/** Samples for ApplicationGateways BackendHealthOnDemand. */
public final class ApplicationGatewaysBackendHealthOnDemandSamples {
    /**
     * Sample code: Test Backend Health.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void testBackendHealth(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .applicationGateways()
            .backendHealthOnDemand(
                "rg1",
                "appgw",
                new ApplicationGatewayOnDemandProbe()
                    .withProtocol(ApplicationGatewayProtocol.HTTP)
                    .withPath("/")
                    .withTimeout(30)
                    .withPickHostnameFromBackendHttpSettings(true)
                    .withBackendAddressPool(
                        new SubResource()
                            .withId(
                                "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationGateways/appgw/backendaddressPools/MFAnalyticsPool"))
                    .withBackendHttpSettings(
                        new SubResource()
                            .withId(
                                "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationGateways/appgw/backendHttpSettingsCollection/MFPoolSettings")),
                null,
                Context.NONE);
    }
}
