// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ApplicationGatewayPrivateEndpointConnections Get. */
public final class ApplicationGatewayPrivateEndpointConnectionsGetSamples {
    /**
     * Sample code: Get Application Gateway Private Endpoint Connection.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getApplicationGatewayPrivateEndpointConnection(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .applicationGatewayPrivateEndpointConnections()
            .getWithResponse("rg1", "appgw", "connection1", Context.NONE);
    }
}
