// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ApplicationGateways GetByResourceGroup. */
public final class ApplicationGatewaysGetByResourceGroupSamples {
    /**
     * Sample code: Get ApplicationGateway.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getApplicationGateway(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.applicationGateways().getByResourceGroupWithResponse("rg1", "appgw", Context.NONE);
    }
}
