// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ApplicationSecurityGroups ListByResourceGroup. */
public final class ApplicationSecurityGroupsListByResourceGroupSamples {
    /**
     * Sample code: List load balancers in resource group.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listLoadBalancersInResourceGroup(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.applicationSecurityGroups().listByResourceGroup("rg1", Context.NONE);
    }
}
