// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for AvailableServiceAliases List. */
public final class AvailableServiceAliasesListSamples {
    /**
     * Sample code: Get available service aliases.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getAvailableServiceAliases(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.availableServiceAliases().list("westcentralus", Context.NONE);
    }
}
