// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for AzureFirewalls ListByResourceGroup. */
public final class AzureFirewallsListByResourceGroupSamples {
    /**
     * Sample code: List all Azure Firewalls for a given resource group.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listAllAzureFirewallsForAGivenResourceGroup(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.azureFirewalls().listByResourceGroup("rg1", Context.NONE);
    }
}
