// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for AzureFirewalls GetByResourceGroup. */
public final class AzureFirewallsGetByResourceGroupSamples {
    /**
     * Sample code: Get Azure Firewall With Additional Properties.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getAzureFirewallWithAdditionalProperties(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.azureFirewalls().getByResourceGroupWithResponse("rg1", "azurefirewall", Context.NONE);
    }

    /**
     * Sample code: Get Azure Firewall With IpGroups.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getAzureFirewallWithIpGroups(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.azureFirewalls().getByResourceGroupWithResponse("rg1", "azurefirewall", Context.NONE);
    }

    /**
     * Sample code: Get Azure Firewall With Zones.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getAzureFirewallWithZones(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.azureFirewalls().getByResourceGroupWithResponse("rg1", "azurefirewall", Context.NONE);
    }

    /**
     * Sample code: Get Azure Firewall With management subnet.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getAzureFirewallWithManagementSubnet(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.azureFirewalls().getByResourceGroupWithResponse("rg1", "azurefirewall", Context.NONE);
    }

    /**
     * Sample code: Get Azure Firewall.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getAzureFirewall(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.azureFirewalls().getByResourceGroupWithResponse("rg1", "azurefirewall", Context.NONE);
    }
}
