// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ConnectionMonitors List. */
public final class ConnectionMonitorsListSamples {
    /**
     * Sample code: List connection monitors.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listConnectionMonitors(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.connectionMonitors().list("rg1", "nw1", Context.NONE);
    }
}
