// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ConnectionMonitors Get. */
public final class ConnectionMonitorsGetSamples {
    /**
     * Sample code: Get connection monitor.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getConnectionMonitor(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.connectionMonitors().getWithResponse("rg1", "nw1", "cm1", Context.NONE);
    }
}
