// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for DdosProtectionPlans GetByResourceGroup. */
public final class DdosProtectionPlansGetByResourceGroupSamples {
    /**
     * Sample code: Get DDoS protection plan.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getDDoSProtectionPlan(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.ddosProtectionPlans().getByResourceGroupWithResponse("rg1", "test-plan", Context.NONE);
    }
}
