// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for DdosProtectionPlans Delete. */
public final class DdosProtectionPlansDeleteSamples {
    /**
     * Sample code: Delete DDoS protection plan.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void deleteDDoSProtectionPlan(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.ddosProtectionPlans().delete("rg1", "test-plan", Context.NONE);
    }
}
