// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteGateways Delete. */
public final class ExpressRouteGatewaysDeleteSamples {
    /**
     * Sample code: ExpressRouteGatewayDelete.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void expressRouteGatewayDelete(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.expressRouteGateways().delete("resourceGroupName", "expressRouteGatewayName", Context.NONE);
    }
}
