// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteCrossConnectionPeerings Get. */
public final class ExpressRouteCrossConnectionPeeringsGetSamples {
    /**
     * Sample code: GetExpressRouteCrossConnectionBgpPeering.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getExpressRouteCrossConnectionBgpPeering(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCrossConnectionPeerings()
            .getWithResponse(
                "CrossConnection-SiliconValley", "<circuitServiceKey>", "AzurePrivatePeering", Context.NONE);
    }
}
