// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteCircuits List. */
public final class ExpressRouteCircuitsListSamples {
    /**
     * Sample code: List ExpressRouteCircuits in a subscription.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listExpressRouteCircuitsInASubscription(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.expressRouteCircuits().list(Context.NONE);
    }
}
