// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.models.ExpressRouteGatewayPropertiesAutoScaleConfiguration;
import com.azure.resourcemanager.network.models.ExpressRouteGatewayPropertiesAutoScaleConfigurationBounds;
import com.azure.resourcemanager.network.models.VirtualHubId;

/** Samples for ExpressRouteGateways CreateOrUpdate. */
public final class ExpressRouteGatewaysCreateOrUpdateSamples {
    /**
     * Sample code: ExpressRouteGatewayCreate.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void expressRouteGatewayCreate(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteGateways()
            .define("gateway-2")
            .withRegion("westus")
            .withExistingResourceGroup("resourceGroupName")
            .withAutoScaleConfiguration(
                new ExpressRouteGatewayPropertiesAutoScaleConfiguration()
                    .withBounds(new ExpressRouteGatewayPropertiesAutoScaleConfigurationBounds().withMin(3)))
            .withVirtualHub(
                new VirtualHubId()
                    .withId(
                        "/subscriptions/subid/resourceGroups/resourceGroupId/providers/Microsoft.Network/virtualHubs/virtualHubName"))
            .create();
    }
}
