// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

/** Samples for ExpressRouteCircuitPeerings CreateOrUpdate. */
public final class ExpressRouteCircuitPeeringsCreateOrUpdateSamples {
    /**
     * Sample code: Create ExpressRouteCircuit Peerings.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createExpressRouteCircuitPeerings(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCircuitPeerings()
            .define("AzurePrivatePeering")
            .withExistingExpressRouteCircuit("rg1", "circuitName")
            .withPeerAsn(200L)
            .withPrimaryPeerAddressPrefix("192.168.16.252/30")
            .withSecondaryPeerAddressPrefix("192.168.18.252/30")
            .withVlanId(200)
            .create();
    }
}
