// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRoutePorts List. */
public final class ExpressRoutePortsListSamples {
    /**
     * Sample code: ExpressRoutePortList.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void expressRoutePortList(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.expressRoutePorts().list(Context.NONE);
    }
}
