// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteCircuitConnections List. */
public final class ExpressRouteCircuitConnectionsListSamples {
    /**
     * Sample code: List ExpressRouteCircuit Connection.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listExpressRouteCircuitConnection(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCircuitConnections()
            .list("rg1", "ExpressRouteARMCircuitA", "AzurePrivatePeering", Context.NONE);
    }
}
