// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteCircuitPeerings Delete. */
public final class ExpressRouteCircuitPeeringsDeleteSamples {
    /**
     * Sample code: Delete ExpressRouteCircuit Peerings.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void deleteExpressRouteCircuitPeerings(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.expressRouteCircuitPeerings().delete("rg1", "circuitName", "peeringName", Context.NONE);
    }
}
