// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.fluent.models.ExpressRouteCrossConnectionPeeringInner;
import com.azure.resourcemanager.network.models.Ipv6ExpressRouteCircuitPeeringConfig;

/** Samples for ExpressRouteCrossConnectionPeerings CreateOrUpdate. */
public final class ExpressRouteCrossConnectionPeeringsCreateOrUpdateSamples {
    /**
     * Sample code: ExpressRouteCrossConnectionBgpPeeringCreate.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void expressRouteCrossConnectionBgpPeeringCreate(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCrossConnectionPeerings()
            .createOrUpdate(
                "CrossConnection-SiliconValley",
                "<circuitServiceKey>",
                "AzurePrivatePeering",
                new ExpressRouteCrossConnectionPeeringInner()
                    .withPeerAsn(200L)
                    .withPrimaryPeerAddressPrefix("192.168.16.252/30")
                    .withSecondaryPeerAddressPrefix("192.168.18.252/30")
                    .withVlanId(200)
                    .withIpv6PeeringConfig(
                        new Ipv6ExpressRouteCircuitPeeringConfig()
                            .withPrimaryPeerAddressPrefix("3FFE:FFFF:0:CD30::/126")
                            .withSecondaryPeerAddressPrefix("3FFE:FFFF:0:CD30::4/126")),
                Context.NONE);
    }
}
