// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteCircuitAuthorizations List. */
public final class ExpressRouteCircuitAuthorizationsListSamples {
    /**
     * Sample code: List ExpressRouteCircuit Authorization.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listExpressRouteCircuitAuthorization(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.expressRouteCircuitAuthorizations().list("rg1", "circuitName", Context.NONE);
    }
}
