// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteCrossConnections ListByResourceGroup. */
public final class ExpressRouteCrossConnectionsListByResourceGroupSamples {
    /**
     * Sample code: ExpressRouteCrossConnectionListByResourceGroup.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void expressRouteCrossConnectionListByResourceGroup(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCrossConnections()
            .listByResourceGroup("CrossConnection-SiliconValley", Context.NONE);
    }
}
