// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ExpressRouteConnections Delete. */
public final class ExpressRouteConnectionsDeleteSamples {
    /**
     * Sample code: ExpressRouteConnectionDelete.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void expressRouteConnectionDelete(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteConnections()
            .delete("resourceGroupName", "expressRouteGatewayName", "connectionName", Context.NONE);
    }
}
