// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.management.SubResource;
import com.azure.resourcemanager.network.models.ExpressRouteCircuitServiceProviderProperties;
import com.azure.resourcemanager.network.models.ExpressRouteCircuitSku;
import com.azure.resourcemanager.network.models.ExpressRouteCircuitSkuFamily;
import com.azure.resourcemanager.network.models.ExpressRouteCircuitSkuTier;
import java.util.Arrays;

/** Samples for ExpressRouteCircuits CreateOrUpdate. */
public final class ExpressRouteCircuitsCreateOrUpdateSamples {
    /**
     * Sample code: Create ExpressRouteCircuit.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createExpressRouteCircuit(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCircuits()
            .define("circuitName")
            .withRegion("Brazil South")
            .withExistingResourceGroup("rg1")
            .withSku(
                new ExpressRouteCircuitSku()
                    .withName("Standard_MeteredData")
                    .withTier(ExpressRouteCircuitSkuTier.STANDARD)
                    .withFamily(ExpressRouteCircuitSkuFamily.METERED_DATA))
            .withAllowClassicOperations(false)
            .withAuthorizations(Arrays.asList())
            .withPeerings(Arrays.asList())
            .withServiceProviderProperties(
                new ExpressRouteCircuitServiceProviderProperties()
                    .withServiceProviderName("Equinix")
                    .withPeeringLocation("Silicon Valley")
                    .withBandwidthInMbps(200))
            .create();
    }

    /**
     * Sample code: Create ExpressRouteCircuit on ExpressRoutePort.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createExpressRouteCircuitOnExpressRoutePort(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCircuits()
            .define("expressRouteCircuit1")
            .withRegion("westus")
            .withExistingResourceGroup("rg1")
            .withSku(
                new ExpressRouteCircuitSku()
                    .withName("Premium_MeteredData")
                    .withTier(ExpressRouteCircuitSkuTier.PREMIUM)
                    .withFamily(ExpressRouteCircuitSkuFamily.METERED_DATA))
            .withExpressRoutePort(
                new SubResource()
                    .withId(
                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/expressRoutePorts/portName"))
            .withBandwidthInGbps(10.0f)
            .create();
    }
}
