// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.GenerateExpressRoutePortsLoaRequest;

/** Samples for ExpressRoutePorts GenerateLoa. */
public final class ExpressRoutePortsGenerateLoaSamples {
    /**
     * Sample code: GenerateExpressRoutePortLOA.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void generateExpressRoutePortLOA(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRoutePorts()
            .generateLoaWithResponse(
                "rg1",
                "portName",
                new GenerateExpressRoutePortsLoaRequest().withCustomerName("customerName"),
                Context.NONE);
    }
}
