// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.management.SubResource;
import com.azure.resourcemanager.network.models.Ipv6CircuitConnectionConfig;

/** Samples for ExpressRouteCircuitConnections CreateOrUpdate. */
public final class ExpressRouteCircuitConnectionsCreateOrUpdateSamples {
    /**
     * Sample code: ExpressRouteCircuitConnectionCreate.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void expressRouteCircuitConnectionCreate(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCircuitConnections()
            .define("circuitConnectionUSAUS")
            .withExistingPeering("rg1", "ExpressRouteARMCircuitA", "AzurePrivatePeering")
            .withExpressRouteCircuitPeering(
                new SubResource()
                    .withId(
                        "/subscriptions/subid1/resourceGroups/dedharcktinit/providers/Microsoft.Network/expressRouteCircuits/dedharcktlocal/peerings/AzurePrivatePeering"))
            .withPeerExpressRouteCircuitPeering(
                new SubResource()
                    .withId(
                        "/subscriptions/subid2/resourceGroups/dedharcktpeer/providers/Microsoft.Network/expressRouteCircuits/dedharcktremote/peerings/AzurePrivatePeering"))
            .withAddressPrefix("10.0.0.0/29")
            .withAuthorizationKey("946a1918-b7a2-4917-b43c-8c4cdaee006a")
            .withIpv6CircuitConnectionConfig(new Ipv6CircuitConnectionConfig().withAddressPrefix("aa:bb::/125"))
            .create();
    }
}
