// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.models.ServiceProviderProvisioningState;

/** Samples for ExpressRouteCrossConnections CreateOrUpdate. */
public final class ExpressRouteCrossConnectionsCreateOrUpdateSamples {
    /**
     * Sample code: UpdateExpressRouteCrossConnection.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void updateExpressRouteCrossConnection(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .expressRouteCrossConnections()
            .define("<circuitServiceKey>")
            .withRegion((String) null)
            .withExistingResourceGroup("CrossConnection-SiliconValley")
            .withServiceProviderProvisioningState(ServiceProviderProvisioningState.NOT_PROVISIONED)
            .create();
    }
}
