// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for HubRouteTables Delete. */
public final class HubRouteTablesDeleteSamples {
    /**
     * Sample code: RouteTableDelete.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void routeTableDelete(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.hubRouteTables().delete("rg1", "virtualHub1", "hubRouteTable1", Context.NONE);
    }
}
