// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for InboundNatRules Delete. */
public final class InboundNatRulesDeleteSamples {
    /**
     * Sample code: InboundNatRuleDelete.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void inboundNatRuleDelete(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.inboundNatRules().delete("testrg", "lb1", "natRule1.1", Context.NONE);
    }
}
