// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for IpAllocations Delete. */
public final class IpAllocationsDeleteSamples {
    /**
     * Sample code: Delete IpAllocation.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void deleteIpAllocation(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.ipAllocations().delete("rg1", "test-ipallocation", Context.NONE);
    }
}
