// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for LoadBalancerBackendAddressPools List. */
public final class LoadBalancerBackendAddressPoolsListSamples {
    /**
     * Sample code: Load balancer with BackendAddressPool containing BackendAddresses.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void loadBalancerWithBackendAddressPoolContainingBackendAddresses(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.loadBalancerBackendAddressPools().list("testrg", "lb", Context.NONE);
    }

    /**
     * Sample code: LoadBalancerBackendAddressPoolList.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void loadBalancerBackendAddressPoolList(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.loadBalancerBackendAddressPools().list("testrg", "lb", Context.NONE);
    }
}
