// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for LoadBalancerOutboundRules Get. */
public final class LoadBalancerOutboundRulesGetSamples {
    /**
     * Sample code: LoadBalancerOutboundRuleGet.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void loadBalancerOutboundRuleGet(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.loadBalancerOutboundRules().getWithResponse("testrg", "lb1", "rule1", Context.NONE);
    }
}
