// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for LocalNetworkGateways GetByResourceGroup. */
public final class LocalNetworkGatewaysGetByResourceGroupSamples {
    /**
     * Sample code: GetLocalNetworkGateway.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getLocalNetworkGateway(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.localNetworkGateways().getByResourceGroupWithResponse("rg1", "localgw", Context.NONE);
    }
}
