// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NatGateways ListByResourceGroup. */
public final class NatGatewaysListByResourceGroupSamples {
    /**
     * Sample code: List nat gateways in resource group.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listNatGatewaysInResourceGroup(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.natGateways().listByResourceGroup("rg1", Context.NONE);
    }
}
