// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.models.VpnNatRuleMapping;
import com.azure.resourcemanager.network.models.VpnNatRuleMode;
import com.azure.resourcemanager.network.models.VpnNatRuleType;
import java.util.Arrays;

/** Samples for NatRules CreateOrUpdate. */
public final class NatRulesCreateOrUpdateSamples {
    /**
     * Sample code: NatRulePut.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void natRulePut(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .natRules()
            .define("natRule1")
            .withExistingVpnGateway("rg1", "gateway1")
            .withTypePropertiesType(VpnNatRuleType.STATIC)
            .withMode(VpnNatRuleMode.EGRESS_SNAT)
            .withInternalMappings(Arrays.asList(new VpnNatRuleMapping().withAddressSpace("10.4.0.0/24")))
            .withExternalMappings(Arrays.asList(new VpnNatRuleMapping().withAddressSpace("192.168.21.0/24")))
            .withIpConfigurationId(
                "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworkGateways/cloudnet1-VNG/ipConfigurations/default")
            .create();
    }
}
