// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NetworkWatchers GetByResourceGroup. */
public final class NetworkWatchersGetByResourceGroupSamples {
    /**
     * Sample code: Get network watcher.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getNetworkWatcher(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.networkWatchers().getByResourceGroupWithResponse("rg1", "nw1", Context.NONE);
    }
}
