// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.QueryTroubleshootingParameters;

/** Samples for NetworkWatchers GetTroubleshootingResult. */
public final class NetworkWatchersGetTroubleshootingResultSamples {
    /**
     * Sample code: Get troubleshoot result.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getTroubleshootResult(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .networkWatchers()
            .getTroubleshootingResult(
                "rg1",
                "nw1",
                new QueryTroubleshootingParameters()
                    .withTargetResourceId(
                        "/subscriptions/subid/resourceGroups/rg2/providers/Microsoft.Compute/virtualMachines/vm1"),
                Context.NONE);
    }
}
