// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NetworkProfiles GetByResourceGroup. */
public final class NetworkProfilesGetByResourceGroupSamples {
    /**
     * Sample code: Get network profile with container network interfaces.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getNetworkProfileWithContainerNetworkInterfaces(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.networkProfiles().getByResourceGroupWithResponse("rg1", "networkProfile1", null, Context.NONE);
    }

    /**
     * Sample code: Get network profile.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getNetworkProfile(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.networkProfiles().getByResourceGroupWithResponse("rg1", "networkProfile1", null, Context.NONE);
    }
}
