// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NetworkInterfaces ListVirtualMachineScaleSetNetworkInterfaces. */
public final class NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesSamples {
    /**
     * Sample code: List virtual machine scale set network interfaces.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listVirtualMachineScaleSetNetworkInterfaces(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.networkInterfaces().listVirtualMachineScaleSetNetworkInterfaces("rg1", "vmss1", Context.NONE);
    }
}
