// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.fluent.models.SecurityRuleInner;
import com.azure.resourcemanager.network.models.SecurityRuleAccess;
import com.azure.resourcemanager.network.models.SecurityRuleDirection;
import com.azure.resourcemanager.network.models.SecurityRuleProtocol;
import java.util.Arrays;

/** Samples for NetworkSecurityGroups CreateOrUpdate. */
public final class NetworkSecurityGroupsCreateOrUpdateSamples {
    /**
     * Sample code: Create network security group with rule.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createNetworkSecurityGroupWithRule(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .networkSecurityGroups()
            .define("testnsg")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withSecurityRules(
                Arrays
                    .asList(
                        new SecurityRuleInner()
                            .withName("rule1")
                            .withProtocol(SecurityRuleProtocol.ASTERISK)
                            .withSourcePortRange("*")
                            .withDestinationPortRange("80")
                            .withSourceAddressPrefix("*")
                            .withDestinationAddressPrefix("*")
                            .withAccess(SecurityRuleAccess.ALLOW)
                            .withPriority(130)
                            .withDirection(SecurityRuleDirection.INBOUND)))
            .create();
    }

    /**
     * Sample code: Create network security group.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createNetworkSecurityGroup(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .networkSecurityGroups()
            .define("testnsg")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .create();
    }
}
