// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NetworkInterfaceTapConfigurations List. */
public final class NetworkInterfaceTapConfigurationsListSamples {
    /**
     * Sample code: List virtual network tap configurations.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listVirtualNetworkTapConfigurations(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.networkInterfaceTapConfigurations().list("rg1", "mynic", Context.NONE);
    }
}
