// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.TroubleshootingParameters;

/** Samples for NetworkWatchers GetTroubleshooting. */
public final class NetworkWatchersGetTroubleshootingSamples {
    /**
     * Sample code: Get troubleshooting.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getTroubleshooting(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .networkWatchers()
            .getTroubleshooting(
                "rg1",
                "nw1",
                new TroubleshootingParameters()
                    .withTargetResourceId(
                        "/subscriptions/subid/resourceGroups/rg2/providers/Microsoft.Compute/virtualMachines/vm1")
                    .withStorageId(
                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/st1")
                    .withStoragePath("https://st1.blob.core.windows.net/cn1"),
                Context.NONE);
    }
}
