// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.management.SubResource;
import com.azure.resourcemanager.network.fluent.models.NetworkInterfaceIpConfigurationInner;
import com.azure.resourcemanager.network.fluent.models.PublicIpAddressInner;
import com.azure.resourcemanager.network.fluent.models.SubnetInner;
import java.util.Arrays;

/** Samples for NetworkInterfaces CreateOrUpdate. */
public final class NetworkInterfacesCreateOrUpdateSamples {
    /**
     * Sample code: Create network interface with Gateway Load Balancer Consumer configured.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createNetworkInterfaceWithGatewayLoadBalancerConsumerConfigured(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .networkInterfaces()
            .define("test-nic")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withIpConfigurations(
                Arrays
                    .asList(
                        new NetworkInterfaceIpConfigurationInner()
                            .withName("ipconfig1")
                            .withGatewayLoadBalancer(
                                new SubResource()
                                    .withId(
                                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/loadBalancers/lb/frontendIPConfigurations/fe-lb-provider"))
                            .withSubnet(
                                new SubnetInner()
                                    .withId(
                                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/rg1-vnet/subnets/default"))
                            .withPublicIpAddress(
                                new PublicIpAddressInner()
                                    .withId(
                                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/publicIPAddresses/test-ip"))))
            .withEnableAcceleratedNetworking(true)
            .create();
    }

    /**
     * Sample code: Create network interface.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createNetworkInterface(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .networkInterfaces()
            .define("test-nic")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withIpConfigurations(
                Arrays
                    .asList(
                        new NetworkInterfaceIpConfigurationInner()
                            .withName("ipconfig1")
                            .withSubnet(
                                new SubnetInner()
                                    .withId(
                                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/rg1-vnet/subnets/default"))
                            .withPublicIpAddress(
                                new PublicIpAddressInner()
                                    .withId(
                                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/publicIPAddresses/test-ip"))))
            .withEnableAcceleratedNetworking(true)
            .create();
    }
}
