// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NetworkInterfaces ListVirtualMachineScaleSetVMNetworkInterfaces. */
public final class NetworkInterfacesListVirtualMachineScaleSetVMNetworkInterfacesSamples {
    /**
     * Sample code: List virtual machine scale set vm network interfaces.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listVirtualMachineScaleSetVmNetworkInterfaces(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .networkInterfaces()
            .listVirtualMachineScaleSetVMNetworkInterfaces("rg1", "vmss1", "1", Context.NONE);
    }
}
