// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NetworkWatchers ListByResourceGroup. */
public final class NetworkWatchersListByResourceGroupSamples {
    /**
     * Sample code: List network watchers.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listNetworkWatchers(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.networkWatchers().listByResourceGroup("rg1", Context.NONE);
    }
}
