// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for NetworkWatchers List. */
public final class NetworkWatchersListSamples {
    /**
     * Sample code: List all network watchers.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listAllNetworkWatchers(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.networkWatchers().list(Context.NONE);
    }
}
