// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for P2SVpnGateways GetP2SVpnConnectionHealth. */
public final class P2SVpnGatewaysGetP2SVpnConnectionHealthSamples {
    /**
     * Sample code: P2SVpnGatewayGetConnectionHealth.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void p2SVpnGatewayGetConnectionHealth(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.p2SVpnGateways().getP2SVpnConnectionHealth("rg1", "p2sVpnGateway1", Context.NONE);
    }
}
