// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for P2SVpnGateways Reset. */
public final class P2SVpnGatewaysResetSamples {
    /**
     * Sample code: ResetP2SVpnGateway.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void resetP2SVpnGateway(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.p2SVpnGateways().reset("rg1", "p2sVpnGateway1", Context.NONE);
    }
}
