// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for P2SVpnGateways List. */
public final class P2SVpnGatewaysListSamples {
    /**
     * Sample code: P2SVpnGatewayListBySubscription.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void p2SVpnGatewayListBySubscription(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.p2SVpnGateways().list(Context.NONE);
    }
}
