// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for PacketCaptures Delete. */
public final class PacketCapturesDeleteSamples {
    /**
     * Sample code: Delete packet capture.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void deletePacketCapture(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.packetCaptures().delete("rg1", "nw1", "pc1", Context.NONE);
    }
}
