// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for PacketCaptures GetStatus. */
public final class PacketCapturesGetStatusSamples {
    /**
     * Sample code: Query packet capture status.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void queryPacketCaptureStatus(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.packetCaptures().getStatus("rg1", "nw1", "pc1", Context.NONE);
    }
}
