// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.fluent.models.SubnetInner;
import com.azure.resourcemanager.network.models.PrivateLinkServiceConnection;
import java.util.Arrays;

/** Samples for PrivateEndpoints CreateOrUpdate. */
public final class PrivateEndpointsCreateOrUpdateSamples {
    /**
     * Sample code: Create private endpoint.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createPrivateEndpoint(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .privateEndpoints()
            .define("testPe")
            .withRegion("eastus2euap")
            .withExistingResourceGroup("rg1")
            .withSubnet(
                new SubnetInner()
                    .withId(
                        "/subscriptions/subId/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/mySubnet"))
            .withPrivateLinkServiceConnections(
                Arrays
                    .asList(
                        new PrivateLinkServiceConnection()
                            .withPrivateLinkServiceId(
                                "/subscriptions/subId/resourceGroups/rg1/providers/Microsoft.Network/privateLinkServices/testPls")
                            .withGroupIds(Arrays.asList("groupIdFromResource"))
                            .withRequestMessage("Please approve my connection.")))
            .create();
    }

    /**
     * Sample code: Create private endpoint with manual approval connection.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createPrivateEndpointWithManualApprovalConnection(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .privateEndpoints()
            .define("testPe")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withSubnet(
                new SubnetInner()
                    .withId(
                        "/subscriptions/subId/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/mySubnet"))
            .withManualPrivateLinkServiceConnections(
                Arrays
                    .asList(
                        new PrivateLinkServiceConnection()
                            .withPrivateLinkServiceId(
                                "/subscriptions/subId/resourceGroups/rg1/providers/Microsoft.Network/privateLinkServices/testPls")
                            .withGroupIds(Arrays.asList("groupIdFromResource"))
                            .withRequestMessage("Please manually approve my connection.")))
            .create();
    }
}
