// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for PrivateLinkServices ListAutoApprovedPrivateLinkServicesByResourceGroup. */
public final class PrivateLinkServicesListAutoApprovedPrivateLinkServicesByResourceGroupSamples {
    /**
     * Sample code: Get list of private link service id that can be linked to a private end point with auto approved.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getListOfPrivateLinkServiceIdThatCanBeLinkedToAPrivateEndPointWithAutoApproved(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .privateLinkServices()
            .listAutoApprovedPrivateLinkServicesByResourceGroup("regionName", "rg1", Context.NONE);
    }
}
