// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for PrivateLinkServices DeletePrivateEndpointConnection. */
public final class PrivateLinkServicesDeletePrivateEndpointConnectionSamples {
    /**
     * Sample code: delete private end point connection for a private link service.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void deletePrivateEndPointConnectionForAPrivateLinkService(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .privateLinkServices()
            .deletePrivateEndpointConnection("rg1", "testPls", "testPlePeConnection", Context.NONE);
    }
}
