// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for PublicIpAddresses ListVirtualMachineScaleSetVMPublicIpAddresses. */
public final class PublicIpAddressesListVirtualMachineScaleSetVMPublicIpAddressesSamples {
    /**
     * Sample code: ListVMSSVMPublicIP.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listVMSSVMPublicIP(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .publicIpAddresses()
            .listVirtualMachineScaleSetVMPublicIpAddresses("vmss-tester", "vmss1", "1", "nic1", "ip1", Context.NONE);
    }
}
