// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for PublicIpPrefixes ListByResourceGroup. */
public final class PublicIpPrefixesListByResourceGroupSamples {
    /**
     * Sample code: List resource group public IP prefixes.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listResourceGroupPublicIPPrefixes(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.publicIpPrefixes().listByResourceGroup("rg1", Context.NONE);
    }
}
