// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for PublicIpAddresses ListByResourceGroup. */
public final class PublicIpAddressesListByResourceGroupSamples {
    /**
     * Sample code: List resource group public IP addresses.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listResourceGroupPublicIPAddresses(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.publicIpAddresses().listByResourceGroup("rg1", Context.NONE);
    }
}
