// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ResourceProvider CheckDnsNameAvailability. */
public final class ResourceProviderCheckDnsNameAvailabilitySamples {
    /**
     * Sample code: Check Dns Name Availability.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void checkDnsNameAvailability(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.resourceProviders().checkDnsNameAvailabilityWithResponse("westus", "testdns", Context.NONE);
    }
}
