// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.fluent.models.RouteFilterRuleInner;
import com.azure.resourcemanager.network.models.Access;
import com.azure.resourcemanager.network.models.RouteFilterRuleType;
import java.util.Arrays;

/** Samples for RouteFilterRules CreateOrUpdate. */
public final class RouteFilterRulesCreateOrUpdateSamples {
    /**
     * Sample code: RouteFilterRuleCreate.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void routeFilterRuleCreate(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .routeFilterRules()
            .createOrUpdate(
                "rg1",
                "filterName",
                "ruleName",
                new RouteFilterRuleInner()
                    .withAccess(Access.ALLOW)
                    .withRouteFilterRuleType(RouteFilterRuleType.COMMUNITY)
                    .withCommunities(Arrays.asList("12076:5030", "12076:5040")),
                Context.NONE);
    }
}
