// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ServiceEndpointPolicies ListByResourceGroup. */
public final class ServiceEndpointPoliciesListByResourceGroupSamples {
    /**
     * Sample code: List resource group service endpoint policies.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listResourceGroupServiceEndpointPolicies(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.serviceEndpointPolicies().listByResourceGroup("rg1", Context.NONE);
    }
}
