// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ServiceEndpointPolicies List. */
public final class ServiceEndpointPoliciesListSamples {
    /**
     * Sample code: List all service endpoint policy.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listAllServiceEndpointPolicy(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.serviceEndpointPolicies().list(Context.NONE);
    }
}
