// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.fluent.models.ServiceEndpointPolicyDefinitionInner;
import java.util.Arrays;

/** Samples for ServiceEndpointPolicyDefinitions CreateOrUpdate. */
public final class ServiceEndpointPolicyDefinitionsCreateOrUpdateSamples {
    /**
     * Sample code: Create service endpoint policy definition.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createServiceEndpointPolicyDefinition(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .serviceEndpointPolicyDefinitions()
            .createOrUpdate(
                "rg1",
                "testPolicy",
                "testDefinition",
                new ServiceEndpointPolicyDefinitionInner()
                    .withDescription("Storage Service EndpointPolicy Definition")
                    .withService("Microsoft.Storage")
                    .withServiceResources(
                        Arrays
                            .asList(
                                "/subscriptions/subid1",
                                "/subscriptions/subid1/resourceGroups/storageRg",
                                "/subscriptions/subid1/resourceGroups/storageRg/providers/Microsoft.Storage/storageAccounts/stAccount")),
                Context.NONE);
    }
}
