// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for ServiceEndpointPolicyDefinitions Get. */
public final class ServiceEndpointPolicyDefinitionsGetSamples {
    /**
     * Sample code: Get service endpoint definition in service endpoint policy.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getServiceEndpointDefinitionInServiceEndpointPolicy(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .serviceEndpointPolicyDefinitions()
            .getWithResponse("rg1", "testPolicy", "testDefinition", Context.NONE);
    }
}
