// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.PrepareNetworkPoliciesRequest;

/** Samples for Subnets PrepareNetworkPolicies. */
public final class SubnetsPrepareNetworkPoliciesSamples {
    /**
     * Sample code: Prepare Network Policies.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void prepareNetworkPolicies(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .subnets()
            .prepareNetworkPolicies(
                "rg1",
                "test-vnet",
                "subnet1",
                new PrepareNetworkPoliciesRequest().withServiceName("Microsoft.Sql/managedInstances"),
                Context.NONE);
    }
}
