// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.UnprepareNetworkPoliciesRequest;

/** Samples for Subnets UnprepareNetworkPolicies. */
public final class SubnetsUnprepareNetworkPoliciesSamples {
    /**
     * Sample code: Unprepare Network Policies.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void unprepareNetworkPolicies(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .subnets()
            .unprepareNetworkPolicies(
                "rg1",
                "test-vnet",
                "subnet1",
                new UnprepareNetworkPoliciesRequest().withServiceName("Microsoft.Sql/managedInstances"),
                Context.NONE);
    }
}
