// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for Subnets Get. */
public final class SubnetsGetSamples {
    /**
     * Sample code: Get subnet.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getSubnet(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.subnets().getWithResponse("subnet-test", "vnetname", "subnet1", null, Context.NONE);
    }

    /**
     * Sample code: Get subnet with a delegation.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getSubnetWithADelegation(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.subnets().getWithResponse("subnet-test", "vnetname", "subnet1", null, Context.NONE);
    }
}
