// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.VpnPacketCaptureStartParameters;

/** Samples for VirtualNetworkGateways StartPacketCapture. */
public final class VirtualNetworkGatewaysStartPacketCaptureSamples {
    /**
     * Sample code: Start packet capture on virtual network gateway with filter.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void startPacketCaptureOnVirtualNetworkGatewayWithFilter(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworkGateways()
            .startPacketCapture(
                "rg1",
                "vpngw",
                new VpnPacketCaptureStartParameters()
                    .withFilterData(
                        "{'TracingFlags': 11,'MaxPacketBufferSize': 120,'MaxFileSize': 200,'Filters':"
                            + " [{'SourceSubnets': ['20.1.1.0/24'],'DestinationSubnets': ['10.1.1.0/24'],'SourcePort':"
                            + " [500],'DestinationPort': [4500],'Protocol': 6,'TcpFlags':"
                            + " 16,'CaptureSingleDirectionTrafficOnly': true}]}"),
                Context.NONE);
    }

    /**
     * Sample code: Start packet capture on virtual network gateway without filter.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void startPacketCaptureOnVirtualNetworkGatewayWithoutFilter(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualNetworkGateways().startPacketCapture("rg1", "vpngw", null, Context.NONE);
    }
}
