// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualRouterPeerings List. */
public final class VirtualRouterPeeringsListSamples {
    /**
     * Sample code: List all Virtual Router Peerings for a given Virtual Router.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void listAllVirtualRouterPeeringsForAGivenVirtualRouter(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualRouterPeerings().list("rg1", "virtualRouter", Context.NONE);
    }
}
