// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualWans List. */
public final class VirtualWansListSamples {
    /**
     * Sample code: VirtualWANList.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void virtualWANList(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualWans().list(Context.NONE);
    }
}
