// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.fluent.models.NetworkInterfaceIpConfigurationInner;

/** Samples for VirtualNetworkTaps CreateOrUpdate. */
public final class VirtualNetworkTapsCreateOrUpdateSamples {
    /**
     * Sample code: Create Virtual Network Tap.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetworkTap(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworkTaps()
            .define("test-vtap")
            .withRegion("centraluseuap")
            .withExistingResourceGroup("rg1")
            .withDestinationNetworkInterfaceIpConfiguration(
                new NetworkInterfaceIpConfigurationInner()
                    .withId(
                        "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/networkInterfaces/testNetworkInterface/ipConfigurations/ipconfig1"))
            .create();
    }
}
