// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualNetworkGateways GetVpnProfilePackageUrl. */
public final class VirtualNetworkGatewaysGetVpnProfilePackageUrlSamples {
    /**
     * Sample code: GetVirtualNetworkGatewayVPNProfilePackageURL.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getVirtualNetworkGatewayVPNProfilePackageURL(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualNetworkGateways().getVpnProfilePackageUrl("rg1", "vpngw", Context.NONE);
    }
}
