// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualHubRouteTableV2S Delete. */
public final class VirtualHubRouteTableV2SDeleteSamples {
    /**
     * Sample code: VirtualHubRouteTableV2Delete.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void virtualHubRouteTableV2Delete(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualHubRouteTableV2S().delete("rg1", "virtualHub1", "virtualHubRouteTable1a", Context.NONE);
    }
}
