// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualHubIpConfiguration List. */
public final class VirtualHubIpConfigurationListSamples {
    /**
     * Sample code: VirtualHubRouteTableV2List.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void virtualHubRouteTableV2List(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualHubIpConfigurations().list("rg1", "hub1", Context.NONE);
    }
}
