// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.VpnClientParameters;

/** Samples for VirtualNetworkGateways Generatevpnclientpackage. */
public final class VirtualNetworkGatewaysGeneratevpnclientpackageSamples {
    /**
     * Sample code: GenerateVPNClientPackage.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void generateVPNClientPackage(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworkGateways()
            .generatevpnclientpackage("rg1", "vpngw", new VpnClientParameters(), Context.NONE);
    }
}
