// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.fluent.models.ServiceEndpointPolicyInner;
import com.azure.resourcemanager.network.fluent.models.SubnetInner;
import com.azure.resourcemanager.network.models.AddressSpace;
import com.azure.resourcemanager.network.models.Delegation;
import com.azure.resourcemanager.network.models.ServiceEndpointPropertiesFormat;
import com.azure.resourcemanager.network.models.VirtualNetworkBgpCommunities;
import java.util.Arrays;

/** Samples for VirtualNetworks CreateOrUpdate. */
public final class VirtualNetworksCreateOrUpdateSamples {
    /**
     * Sample code: Create virtual network with subnet.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetworkWithSubnet(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworks()
            .define("test-vnet")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withAddressSpace(new AddressSpace().withAddressPrefixes(Arrays.asList("10.0.0.0/16")))
            .withSubnets(Arrays.asList(new SubnetInner().withName("test-1").withAddressPrefix("10.0.0.0/24")))
            .create();
    }

    /**
     * Sample code: Create virtual network with Bgp Communities.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetworkWithBgpCommunities(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworks()
            .define("test-vnet")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withAddressSpace(new AddressSpace().withAddressPrefixes(Arrays.asList("10.0.0.0/16")))
            .withSubnets(Arrays.asList(new SubnetInner().withName("test-1").withAddressPrefix("10.0.0.0/24")))
            .withBgpCommunities(new VirtualNetworkBgpCommunities().withVirtualNetworkCommunity("12076:20000"))
            .create();
    }

    /**
     * Sample code: Create virtual network with subnet containing address prefixes.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetworkWithSubnetContainingAddressPrefixes(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworks()
            .define("test-vnet")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withAddressSpace(new AddressSpace().withAddressPrefixes(Arrays.asList("10.0.0.0/16")))
            .withSubnets(
                Arrays
                    .asList(
                        new SubnetInner()
                            .withName("test-2")
                            .withAddressPrefixes(Arrays.asList("10.0.0.0/28", "10.0.1.0/28"))))
            .create();
    }

    /**
     * Sample code: Create virtual network with delegated subnets.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetworkWithDelegatedSubnets(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworks()
            .define("test-vnet")
            .withRegion("westcentralus")
            .withExistingResourceGroup("rg1")
            .withAddressSpace(new AddressSpace().withAddressPrefixes(Arrays.asList("10.0.0.0/16")))
            .withSubnets(
                Arrays
                    .asList(
                        new SubnetInner()
                            .withName("test-1")
                            .withAddressPrefix("10.0.0.0/24")
                            .withDelegations(
                                Arrays
                                    .asList(
                                        new Delegation()
                                            .withName("myDelegation")
                                            .withServiceName("Microsoft.Sql/managedInstances")))))
            .create();
    }

    /**
     * Sample code: Create virtual network.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetwork(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworks()
            .define("test-vnet")
            .withRegion("eastus")
            .withExistingResourceGroup("rg1")
            .withAddressSpace(new AddressSpace().withAddressPrefixes(Arrays.asList("10.0.0.0/16")))
            .withFlowTimeoutInMinutes(10)
            .create();
    }

    /**
     * Sample code: Create virtual network with service endpoints and service endpoint policy.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetworkWithServiceEndpointsAndServiceEndpointPolicy(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworks()
            .define("vnet1")
            .withRegion("eastus2euap")
            .withExistingResourceGroup("vnetTest")
            .withAddressSpace(new AddressSpace().withAddressPrefixes(Arrays.asList("10.0.0.0/16")))
            .withSubnets(
                Arrays
                    .asList(
                        new SubnetInner()
                            .withName("test-1")
                            .withAddressPrefix("10.0.0.0/16")
                            .withServiceEndpoints(
                                Arrays.asList(new ServiceEndpointPropertiesFormat().withService("Microsoft.Storage")))
                            .withServiceEndpointPolicies(
                                Arrays
                                    .asList(
                                        new ServiceEndpointPolicyInner()
                                            .withId(
                                                "/subscriptions/subid/resourceGroups/vnetTest/providers/Microsoft.Network/serviceEndpointPolicies/ServiceEndpointPolicy1")))))
            .create();
    }

    /**
     * Sample code: Create virtual network with service endpoints.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createVirtualNetworkWithServiceEndpoints(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworks()
            .define("vnet1")
            .withRegion("eastus")
            .withExistingResourceGroup("vnetTest")
            .withAddressSpace(new AddressSpace().withAddressPrefixes(Arrays.asList("10.0.0.0/16")))
            .withSubnets(
                Arrays
                    .asList(
                        new SubnetInner()
                            .withName("test-1")
                            .withAddressPrefix("10.0.0.0/16")
                            .withServiceEndpoints(
                                Arrays.asList(new ServiceEndpointPropertiesFormat().withService("Microsoft.Storage")))))
            .create();
    }
}
