// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.resourcemanager.network.models.BreakOutCategoryPolicies;
import com.azure.resourcemanager.network.models.Office365PolicyProperties;

/** Samples for VirtualApplianceSites CreateOrUpdate. */
public final class VirtualApplianceSitesCreateOrUpdateSamples {
    /**
     * Sample code: Create Network Virtual Appliance Site.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createNetworkVirtualApplianceSite(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualApplianceSites()
            .define("site1")
            .withExistingNetworkVirtualAppliance("rg1", "nva")
            .withAddressPrefix("192.168.1.0/24")
            .withO365Policy(
                new Office365PolicyProperties()
                    .withBreakOutCategories(
                        new BreakOutCategoryPolicies().withAllow(true).withOptimize(true).withDefaultProperty(true)))
            .create();
    }
}
