// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualRouterPeerings Delete. */
public final class VirtualRouterPeeringsDeleteSamples {
    /**
     * Sample code: Delete VirtualRouterPeering.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void deleteVirtualRouterPeering(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualRouterPeerings().delete("rg1", "virtualRouter", "peering1", Context.NONE);
    }
}
