// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualHubs GetByResourceGroup. */
public final class VirtualHubsGetByResourceGroupSamples {
    /**
     * Sample code: VirtualHubGet.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void virtualHubGet(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualHubs().getByResourceGroupWithResponse("rg1", "virtualHub1", Context.NONE);
    }
}
