// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualNetworkGateways Reset. */
public final class VirtualNetworkGatewaysResetSamples {
    /**
     * Sample code: ResetVirtualNetworkGateway.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void resetVirtualNetworkGateway(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualNetworkGateways().reset("rg1", "vpngw", null, Context.NONE);
    }
}
