// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VirtualHubRouteTableV2S List. */
public final class VirtualHubRouteTableV2SListSamples {
    /**
     * Sample code: VirtualHubRouteTableV2List.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void virtualHubRouteTableV2List(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.virtualHubRouteTableV2S().list("rg1", "virtualHub1", Context.NONE);
    }
}
