// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.management.SubResource;
import com.azure.resourcemanager.network.models.SyncRemoteAddressSpace;

/** Samples for VirtualNetworkPeerings CreateOrUpdate. */
public final class VirtualNetworkPeeringsCreateOrUpdateSamples {
    /**
     * Sample code: Sync Peering.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void syncPeering(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworkPeerings()
            .define("peer")
            .withExistingVirtualNetwork("peerTest", "vnet1")
            .withAllowVirtualNetworkAccess(true)
            .withAllowForwardedTraffic(true)
            .withAllowGatewayTransit(false)
            .withUseRemoteGateways(false)
            .withRemoteVirtualNetwork(
                new SubResource()
                    .withId(
                        "/subscriptions/subid/resourceGroups/peerTest/providers/Microsoft.Network/virtualNetworks/vnet2"))
            .withSyncRemoteAddressSpace(SyncRemoteAddressSpace.TRUE)
            .create();
    }

    /**
     * Sample code: Create peering.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void createPeering(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworkPeerings()
            .define("peer")
            .withExistingVirtualNetwork("peerTest", "vnet1")
            .withAllowVirtualNetworkAccess(true)
            .withAllowForwardedTraffic(true)
            .withAllowGatewayTransit(false)
            .withUseRemoteGateways(false)
            .withRemoteVirtualNetwork(
                new SubResource()
                    .withId(
                        "/subscriptions/subid/resourceGroups/peerTest/providers/Microsoft.Network/virtualNetworks/vnet2"))
            .create();
    }
}
