// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.VpnDeviceScriptParameters;

/** Samples for VirtualNetworkGateways VpnDeviceConfigurationScript. */
public final class VirtualNetworkGatewaysVpnDeviceConfigurationScriptSamples {
    /**
     * Sample code: GetVPNDeviceConfigurationScript.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getVPNDeviceConfigurationScript(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .virtualNetworkGateways()
            .vpnDeviceConfigurationScriptWithResponse(
                "rg1",
                "vpngw",
                new VpnDeviceScriptParameters()
                    .withVendor("Cisco")
                    .withDeviceFamily("ISR")
                    .withFirmwareVersion("IOS 15.1 (Preview)"),
                Context.NONE);
    }
}
