// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VpnGateways GetByResourceGroup. */
public final class VpnGatewaysGetByResourceGroupSamples {
    /**
     * Sample code: VpnGatewayGet.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void vpnGatewayGet(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.vpnGateways().getByResourceGroupWithResponse("rg1", "gateway1", Context.NONE);
    }
}
