// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.VpnGatewayPacketCaptureStartParameters;

/** Samples for VpnGateways StartPacketCapture. */
public final class VpnGatewaysStartPacketCaptureSamples {
    /**
     * Sample code: Start packet capture on vpn gateway with filter.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void startPacketCaptureOnVpnGatewayWithFilter(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .vpnGateways()
            .startPacketCapture(
                "rg1",
                "vpngw",
                new VpnGatewayPacketCaptureStartParameters()
                    .withFilterData(
                        "{'TracingFlags': 11,'MaxPacketBufferSize': 120,'MaxFileSize': 200,'Filters':"
                            + " [{'SourceSubnets': ['20.1.1.0/24'],'DestinationSubnets': ['10.1.1.0/24'],'SourcePort':"
                            + " [500],'DestinationPort': [4500],'Protocol': 6,'TcpFlags':"
                            + " 16,'CaptureSingleDirectionTrafficOnly': true}]}"),
                Context.NONE);
    }

    /**
     * Sample code: Start packet capture on vpn gateway without filter.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void startPacketCaptureOnVpnGatewayWithoutFilter(
        com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.vpnGateways().startPacketCapture("rg1", "vpngw", null, Context.NONE);
    }
}
