// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VpnLinkConnections ListByVpnConnection. */
public final class VpnLinkConnectionsListByVpnConnectionSamples {
    /**
     * Sample code: VpnSiteLinkConnectionList.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void vpnSiteLinkConnectionList(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.vpnLinkConnections().listByVpnConnection("rg1", "gateway1", "vpnConnection1", Context.NONE);
    }
}
