// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VpnLinkConnections GetIkeSas. */
public final class VpnLinkConnectionsGetIkeSasSamples {
    /**
     * Sample code: GetVpnLinkConnectionIkeSa.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void getVpnLinkConnectionIkeSa(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .vpnLinkConnections()
            .getIkeSas("rg1", "gateway1", "vpnConnection1", "Connection-Link1", Context.NONE);
    }
}
