// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;

/** Samples for VpnSites Delete. */
public final class VpnSitesDeleteSamples {
    /**
     * Sample code: VpnSiteDelete.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void vpnSiteDelete(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager.vpnSites().delete("rg1", "vpnSite1", Context.NONE);
    }
}
