// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.network;

import com.azure.core.util.Context;
import com.azure.resourcemanager.network.models.GetVpnSitesConfigurationRequest;
import java.util.Arrays;

/** Samples for VpnSitesConfiguration Download. */
public final class VpnSitesConfigurationDownloadSamples {
    /**
     * Sample code: VpnSitesConfigurationDownload.
     *
     * @param networkManager Entry point to NetworkManager. Network Client.
     */
    public static void vpnSitesConfigurationDownload(com.azure.resourcemanager.network.NetworkManager networkManager) {
        networkManager
            .vpnSitesConfigurations()
            .download(
                "rg1",
                "wan1",
                new GetVpnSitesConfigurationRequest()
                    .withVpnSites(
                        Arrays
                            .asList("/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/vpnSites/abc"))
                    .withOutputBlobSasUrl(
                        "https://blobcortextesturl.blob.core.windows.net/folderforconfig/vpnFile?sp=rw&se=2018-01-10T03%3A42%3A04Z&sv=2017-04-17&sig=WvXrT5bDmDFfgHs%2Brz%2BjAu123eRCNE9BO0eQYcPDT7pY%3D&sr=b"),
                Context.NONE);
    }
}
