// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CapacityReservationGroups GetByResourceGroup. */
public final class CapacityReservationGroupsGetByResourceGroupSamples {
    /**
     * Sample code: Get a capacity reservation Group.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getACapacityReservationGroup(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .capacityReservationGroups()
            .getByResourceGroupWithResponse("myResourceGroup", "myCapacityReservationGroup", null, Context.NONE);
    }
}
