// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;
import com.azure.resourcemanager.compute.models.ExpandTypesForGetCapacityReservationGroups;

/** Samples for CapacityReservationGroups List. */
public final class CapacityReservationGroupsListSamples {
    /**
     * Sample code: List capacity reservation groups in subscription.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listCapacityReservationGroupsInSubscription(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .capacityReservationGroups()
            .list(ExpandTypesForGetCapacityReservationGroups.VIRTUAL_MACHINES_REF, Context.NONE);
    }
}
