// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CapacityReservations ListByCapacityReservationGroup. */
public final class CapacityReservationsListByCapacityReservationGroupSamples {
    /**
     * Sample code: List capacity reservations in reservation group.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listCapacityReservationsInReservationGroup(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .capacityReservations()
            .listByCapacityReservationGroup("myResourceGroup", "myCapacityReservationGroup", Context.NONE);
    }
}
