// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServices List. */
public final class CloudServicesListSamples {
    /**
     * Sample code: List Cloud Services in a Subscription.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listCloudServicesInASubscription(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.cloudServices().list(Context.NONE);
    }
}
