// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServicesUpdateDomain ListUpdateDomains. */
public final class CloudServicesUpdateDomainListUpdateDomainsSamples {
    /**
     * Sample code: List Update Domains in Cloud Service.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listUpdateDomainsInCloudService(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.cloudServicesUpdateDomains().listUpdateDomains("ConstosoRG", "{cs-name}", Context.NONE);
    }
}
