// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServices GetByResourceGroup. */
public final class CloudServicesGetByResourceGroupSamples {
    /**
     * Sample code: Get Cloud Service with Multiple Roles and RDP Extension.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getCloudServiceWithMultipleRolesAndRDPExtension(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.cloudServices().getByResourceGroupWithResponse("ConstosoRG", "{cs-name}", Context.NONE);
    }
}
