// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServiceRoles List. */
public final class CloudServiceRolesListSamples {
    /**
     * Sample code: List Roles in a Cloud Service.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listRolesInACloudService(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.cloudServiceRoles().list("ConstosoRG", "{cs-name}", Context.NONE);
    }
}
