// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServices GetInstanceView. */
public final class CloudServicesGetInstanceViewSamples {
    /**
     * Sample code: Get Cloud Service Instance View with Multiple Roles.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getCloudServiceInstanceViewWithMultipleRoles(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.cloudServices().getInstanceViewWithResponse("ConstosoRG", "{cs-name}", Context.NONE);
    }
}
