// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServiceRoleInstances Get. */
public final class CloudServiceRoleInstancesGetSamples {
    /**
     * Sample code: Get Cloud Service Role Instance.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getCloudServiceRoleInstance(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .cloudServiceRoleInstances()
            .getWithResponse("{roleInstance-name}", "ConstosoRG", "{cs-name}", null, Context.NONE);
    }
}
