// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServiceRoleInstances Rebuild. */
public final class CloudServiceRoleInstancesRebuildSamples {
    /**
     * Sample code: Rebuild Cloud Service Role Instance.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void rebuildCloudServiceRoleInstance(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .cloudServiceRoleInstances()
            .rebuild("{roleInstance-name}", "ConstosoRG", "{cs-name}", Context.NONE);
    }
}
