// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServiceOperatingSystems ListOSVersions. */
public final class CloudServiceOperatingSystemsListOSVersionsSamples {
    /**
     * Sample code: List Cloud Service OS Versions in a subscription.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listCloudServiceOSVersionsInASubscription(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.cloudServiceOperatingSystems().listOSVersions("westus2", Context.NONE);
    }
}
