// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for CloudServices Delete. */
public final class CloudServicesDeleteSamples {
    /**
     * Sample code: Delete Cloud Service.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void deleteCloudService(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.cloudServices().delete("ConstosoRG", "{cs-name}", Context.NONE);
    }
}
