// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for DedicatedHostGroups GetByResourceGroup. */
public final class DedicatedHostGroupsGetByResourceGroupSamples {
    /**
     * Sample code: Create a dedicated host group.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void createADedicatedHostGroup(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .dedicatedHostGroups()
            .getByResourceGroupWithResponse("myResourceGroup", "myDedicatedHostGroup", null, Context.NONE);
    }
}
