// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for DiskEncryptionSets ListAssociatedResources. */
public final class DiskEncryptionSetsListAssociatedResourcesSamples {
    /**
     * Sample code: List all resources that are encrypted with this disk encryption set.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listAllResourcesThatAreEncryptedWithThisDiskEncryptionSet(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .diskEncryptionSets()
            .listAssociatedResources("myResourceGroup", "myDiskEncryptionSet", Context.NONE);
    }
}
