// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for DiskAccesses ListByResourceGroup. */
public final class DiskAccessesListByResourceGroupSamples {
    /**
     * Sample code: List all disk access resources in a resource group.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listAllDiskAccessResourcesInAResourceGroup(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.diskAccesses().listByResourceGroup("myResourceGroup", Context.NONE);
    }
}
