// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for DiskAccesses List. */
public final class DiskAccessesListSamples {
    /**
     * Sample code: List all disk access resources in a subscription.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listAllDiskAccessResourcesInASubscription(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.diskAccesses().list(Context.NONE);
    }
}
