// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for GalleryImages Get. */
public final class GalleryImagesGetSamples {
    /**
     * Sample code: Get a gallery image.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getAGalleryImage(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .galleryImages()
            .getWithResponse("myResourceGroup", "myGalleryName", "myGalleryImageName", Context.NONE);
    }
}
