// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for GalleryApplications Delete. */
public final class GalleryApplicationsDeleteSamples {
    /**
     * Sample code: Delete a gallery Application.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void deleteAGalleryApplication(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .galleryApplications()
            .delete("myResourceGroup", "myGalleryName", "myGalleryApplicationName", Context.NONE);
    }
}
