// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;
import com.azure.resourcemanager.compute.models.GalleryImage;
import com.azure.resourcemanager.compute.models.GalleryImageIdentifier;
import com.azure.resourcemanager.compute.models.HyperVGeneration;
import com.azure.resourcemanager.compute.models.OperatingSystemStateTypes;
import com.azure.resourcemanager.compute.models.OperatingSystemTypes;

/** Samples for GalleryImages Update. */
public final class GalleryImagesUpdateSamples {
    /**
     * Sample code: Update a simple gallery image.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void updateASimpleGalleryImage(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        GalleryImage resource =
            computeManager
                .galleryImages()
                .getWithResponse("myResourceGroup", "myGalleryName", "myGalleryImageName", Context.NONE)
                .getValue();
        resource
            .update()
            .withOsType(OperatingSystemTypes.WINDOWS)
            .withOsState(OperatingSystemStateTypes.GENERALIZED)
            .withHyperVGeneration(HyperVGeneration.V1)
            .withIdentifier(
                new GalleryImageIdentifier()
                    .withPublisher("myPublisherName")
                    .withOffer("myOfferName")
                    .withSku("mySkuName"))
            .apply();
    }
}
