// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;
import com.azure.resourcemanager.compute.models.ThrottledRequestsInput;
import java.time.OffsetDateTime;

/** Samples for LogAnalytics ExportThrottledRequests. */
public final class LogAnalyticsExportThrottledRequestsSamples {
    /**
     * Sample code: Export logs which contain all throttled Api requests made to Compute Resource Provider within the
     * given time period.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void
        exportLogsWhichContainAllThrottledApiRequestsMadeToComputeResourceProviderWithinTheGivenTimePeriod(
            com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .logAnalytics()
            .exportThrottledRequests(
                "westus",
                new ThrottledRequestsInput()
                    .withBlobContainerSasUri("https://somesasuri")
                    .withFromTime(OffsetDateTime.parse("2018-01-21T01:54:06.862601Z"))
                    .withToTime(OffsetDateTime.parse("2018-01-23T01:54:06.862601Z"))
                    .withGroupByOperationName(true)
                    .withGroupByResourceName(false)
                    .withGroupByClientApplicationId(false)
                    .withGroupByUserAgent(false),
                Context.NONE);
    }
}
