// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for RestorePoints Get. */
public final class RestorePointsGetSamples {
    /**
     * Sample code: Get a restore point.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getARestorePoint(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.restorePoints().getWithResponse("myResourceGroup", "rpcName", "rpName", Context.NONE);
    }
}
