// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for RestorePointCollections GetByResourceGroup. */
public final class RestorePointCollectionsGetByResourceGroupSamples {
    /**
     * Sample code: Get a restore point collection, including the restore points contained in the restore point
     * collection.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getARestorePointCollectionIncludingTheRestorePointsContainedInTheRestorePointCollection(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .restorePointCollections()
            .getByResourceGroupWithResponse("myResourceGroup", "rpcName", null, Context.NONE);
    }

    /**
     * Sample code: Get a restore point collection (but not the restore points contained in the restore point
     * collection).
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getARestorePointCollectionButNotTheRestorePointsContainedInTheRestorePointCollection(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .restorePointCollections()
            .getByResourceGroupWithResponse("myResourceGroup", "myRpc", null, Context.NONE);
    }
}
