// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for Snapshots GetByResourceGroup. */
public final class SnapshotsGetByResourceGroupSamples {
    /**
     * Sample code: Get information about a snapshot.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getInformationAboutASnapshot(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.snapshots().getByResourceGroupWithResponse("myResourceGroup", "mySnapshot", Context.NONE);
    }
}
