// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

/** Samples for SshPublicKeys Create. */
public final class SshPublicKeysCreateSamples {
    /**
     * Sample code: Create a new SSH public key resource.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void createANewSSHPublicKeyResource(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .sshPublicKeys()
            .define("mySshPublicKeyName")
            .withRegion("westus")
            .withExistingResourceGroup("myResourceGroup")
            .withPublicKey("{ssh-rsa public key}")
            .create();
    }
}
