// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for SshPublicKeys GetByResourceGroup. */
public final class SshPublicKeysGetByResourceGroupSamples {
    /**
     * Sample code: Get an ssh public key.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getAnSshPublicKey(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .sshPublicKeys()
            .getByResourceGroupWithResponse("myResourceGroup", "mySshPublicKeyName", Context.NONE);
    }
}
