// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for VirtualMachineScaleSetVMs Get. */
public final class VirtualMachineScaleSetVMsGetSamples {
    /**
     * Sample code: Get VM scale set VM with UserData.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getVMScaleSetVMWithUserData(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .virtualMachineScaleSetVMs()
            .getWithResponse("myResourceGroup", "{vmss-name}", "0", null, Context.NONE);
    }
}
