// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for VirtualMachines Generalize. */
public final class VirtualMachinesGeneralizeSamples {
    /**
     * Sample code: Generalize a Virtual Machine.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void generalizeAVirtualMachine(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.virtualMachines().generalizeWithResponse("myResourceGroup", "myVMName", Context.NONE);
    }
}
