// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;
import com.azure.resourcemanager.compute.models.VirtualMachineRunCommand;
import com.azure.resourcemanager.compute.models.VirtualMachineRunCommandScriptSource;

/** Samples for VirtualMachineRunCommands Update. */
public final class VirtualMachineRunCommandsUpdateSamples {
    /**
     * Sample code: Update a run command.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void updateARunCommand(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        VirtualMachineRunCommand resource =
            computeManager
                .virtualMachineRunCommands()
                .getByVirtualMachineWithResponse("myResourceGroup", "myVM", "myRunCommand", null, Context.NONE)
                .getValue();
        resource
            .update()
            .withSource(new VirtualMachineRunCommandScriptSource().withScript("Write-Host Script Source Updated!"))
            .apply();
    }
}
