// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for VirtualMachineScaleSetVMs GetInstanceView. */
public final class VirtualMachineScaleSetVMsGetInstanceViewSamples {
    /**
     * Sample code: Get instance view of a virtual machine from a VM scale set placed on a dedicated host group through
     * automatic placement.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void
        getInstanceViewOfAVirtualMachineFromAVMScaleSetPlacedOnADedicatedHostGroupThroughAutomaticPlacement(
            com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .virtualMachineScaleSetVMs()
            .getInstanceViewWithResponse("myResourceGroup", "myVirtualMachineScaleSet", "0", Context.NONE);
    }
}
