// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for VirtualMachines ListAvailableSizes. */
public final class VirtualMachinesListAvailableSizesSamples {
    /**
     * Sample code: Lists all available virtual machine sizes to which the specified virtual machine can be resized.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listsAllAvailableVirtualMachineSizesToWhichTheSpecifiedVirtualMachineCanBeResized(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.virtualMachines().listAvailableSizes("myResourceGroup", "myVmName", Context.NONE);
    }
}
