// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for VirtualMachines ListByLocation. */
public final class VirtualMachinesListByLocationSamples {
    /**
     * Sample code: Lists all the virtual machines under the specified subscription for the specified location.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void listsAllTheVirtualMachinesUnderTheSpecifiedSubscriptionForTheSpecifiedLocation(
        com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager.virtualMachines().listByLocation("eastus", Context.NONE);
    }
}
