// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute;

import com.azure.core.util.Context;

/** Samples for VirtualMachineRunCommands GetByVirtualMachine. */
public final class VirtualMachineRunCommandsGetByVirtualMachineSamples {
    /**
     * Sample code: Get a run command.
     *
     * @param computeManager Entry point to ComputeManager. Compute Client.
     */
    public static void getARunCommand(com.azure.resourcemanager.compute.ComputeManager computeManager) {
        computeManager
            .virtualMachineRunCommands()
            .getByVirtualMachineWithResponse("myResourceGroup", "myVM", "myRunCommand", null, Context.NONE);
    }
}
