// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.policy;

import com.azure.core.util.Context;

/** Samples for PolicyAssignments GetById. */
public final class PolicyAssignmentsGetByIdSamples {
    /**
     * Sample code: Retrieve a policy assignment by ID.
     *
     * @param policyManager Entry point to PolicyManager. To manage and control access to your resources, you can define
     *     customized policies and assign them at a scope.
     */
    public static void retrieveAPolicyAssignmentByID(com.azure.resourcemanager.policy.PolicyManager policyManager) {
        policyManager
            .policyAssignments()
            .getByIdWithResponse(
                "providers/Microsoft.Management/managementGroups/MyManagementGroup/providers/Microsoft.Authorization/policyAssignments/LowCostStorage",
                Context.NONE);
    }

    /**
     * Sample code: Retrieve a policy assignment with a managed identity by ID.
     *
     * @param policyManager Entry point to PolicyManager. To manage and control access to your resources, you can define
     *     customized policies and assign them at a scope.
     */
    public static void retrieveAPolicyAssignmentWithAManagedIdentityByID(
        com.azure.resourcemanager.policy.PolicyManager policyManager) {
        policyManager
            .policyAssignments()
            .getByIdWithResponse(
                "providers/Microsoft.Management/managementGroups/MyManagementGroup/providers/Microsoft.Authorization/policyAssignments/LowCostStorage",
                Context.NONE);
    }
}
