// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.policy;

import com.azure.core.util.Context;

/** Samples for PolicyExemptions List. */
public final class PolicyExemptionsListSamples {
    /**
     * Sample code: List policy exemptions that apply to a subscription.
     *
     * @param policyManager Entry point to PolicyManager. To manage and control access to your resources, you can define
     *     customized policies and assign them at a scope.
     */
    public static void listPolicyExemptionsThatApplyToASubscription(
        com.azure.resourcemanager.policy.PolicyManager policyManager) {
        policyManager.policyExemptions().list("atScope()", Context.NONE);
    }
}
