// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute.implementation;

import com.azure.resourcemanager.compute.fluent.models.OSVersionInner;
import com.azure.resourcemanager.compute.models.OSVersion;
import com.azure.resourcemanager.compute.models.OSVersionProperties;

public final class OSVersionImpl implements OSVersion {
    private OSVersionInner innerObject;

    private final com.azure.resourcemanager.compute.ComputeManager serviceManager;

    OSVersionImpl(OSVersionInner innerObject, com.azure.resourcemanager.compute.ComputeManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public OSVersionProperties properties() {
        return this.innerModel().properties();
    }

    public OSVersionInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.compute.ComputeManager manager() {
        return this.serviceManager;
    }
}
